config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homepage/index'

  resources :products

  resources :users, except: [:new, :create] do
    resources :cart_items, except: [:new]
  end
  root 'homepage#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart

  def self.build_from_product(product)
    new(name: product.name, price: product.price)
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :price, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
  has_one :cart
  has_many :cart_items, through: :cart

  before_create :add_cart

private
  def add_cart
    self.build_cart
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	def new
	end

	def create
		@cart = Cart.new
		@cart.save
	end

	def show
	end

	def edit
	end

	def update
	end

	def destroy
	end




end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController

  before_action :authenticate_user!

  def index
    @cart_items = CartItem.all
  end

  def create
    product = Product.find(params[:product_id])
    @cart_item = CartItem.build_from_product(product)

    if @cart_item.save
      redirect_to user_cart_items_path(@cart_item)

    else
      render 'new'
    end
  end

  def show
    @cart_item = CartItem.find(params[:id])
  end

  def edit
    @cart_item = CartItem.find(params[:id])
  end

  def update
    @cart_item = CartItem.find(params[:id])

    if @cart_item.update(cart_item_params)
      redirect_to @cart_item
    else
      render 'edit'
    end
  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    redirect_to user_cart_items_path
  end

  private
    def cart_item_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
  end

  def index
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
   
    redirect_to products_path
  end

  private
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def index
  # end

  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   puts "after user"
  #   @user.cart = Cart.create
  #   puts @user.cart
  #   if @user.save
  #     redirect to @user
  #   else
  #     render 'new'
  #   end
  # end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/_form.html.erb
<%= form_for [current_user, @cart_item] do |f| %>
  <% if @cart_item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited
      this cart_item from being saved:</h2>
    <ul>
    <% @cart_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing cart item</h1>

<%= render 'form' %>

<%= link_to 'Back', user_cart_items_path %>

app/views/cart_items/index.html.erb
<h1>Your shopping cart</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th colspan="2"></th>
  </tr>

  <% @cart_items.each do |cart_item| %>
    <tr>
      <td><%= cart_item.name %></td>
      <td><%= cart_item.price %></td>
      <td><%= link_to 'Show', user_cart_item_path(current_user, cart_item) %></td>
      <td><%= link_to 'Edit', edit_user_cart_item_path(current_user, cart_item) %></td>
      <td><%= link_to 'Destroy', user_cart_item_path(current_user, cart_item),
                          method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cart_items/new.html.erb
<h1>New cart item</h1>

<%= render 'form' %>


<%= link_to 'Back', user_cart_items_path %>

app/views/cart_items/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @cart_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart_item.price %>
</p>

<%= link_to 'Back', user_cart_items_path %>
<%= link_to 'Destroy', user_cart_item_path(current_user, @cart_item),
                          method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/homepage/index.html.erb
<h1>Homepage#index</h1>
<p>Find me in app/views/homepage/index.html.erb</p>
<%= link_to 'Enter', controller: 'products' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingCart</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= link_to 'Home', homepage_index_path %>
  <%= link_to 'Shopping Cart', user_cart_items_path(current_user) %>


    <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
    <h3>Hello <%= current_user.email %></h3>
<% else %>
  <%= link_to 'Sign In', user_session_path, :method => :post %>
<% end %>

<%= yield %>


</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited
      this product from being saved:</h2>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th colspan="2"></th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', product_path(product) %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>


<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Back', products_path %>

<%= form_tag "/users/#{current_user.id}/cart_items" do %>
  <%= hidden_field_tag :product_id, @product.id %>
  <%= submit_tag 'add to cart' %>
<% end %>